# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.1
_src_path: https://github.com/jupyterlab/extension-template
author_email: j.windgassen@fz-juelich.de
author_name: Jonathan Windgassen
has_binder: false
has_settings: true
kind: server
labextension_name: jupyterlab-trame-manager
project_short_description: A JupyterLab extension.
python_name: jupyterlab_trame_manager
repository: https://github.com/github_username/jupyterlab-trame-manager.git
test: false

